# -*- coding: utf-8 -*-
"""Hand_Signals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JO5wbC9WYieO77INnM3RquSYW9t9U6k1
"""

import tensorflow as tf

tf.keras.utils.set_random_seed(30)
tf.config.experimental.enable_op_determinism()

from tensorflow.keras import datasets
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


train_df = pd.read_csv("sign_mnist_train.csv")
test_df  = pd.read_csv("sign_mnist_test.csv")

# create labels (index)

y_train = train_df.pop("label")
y_test = test_df.pop("label")
print(y_train)

# Get unique labels and create a mapping to consecutive integers (0 to num_classes - 1)
unique_labels = np.unique(y_train)


x_train = train_df.values.reshape(-1,28,28,1).astype("float32") / 255.0
x_test = test_df.values.reshape(-1,28,28,1).astype("float32") / 255.0


"""END OF DATA PREPROCESSING"""

import matplotlib.pyplot as plt
import numpy as np

Uppercase= ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

unique_labels = np.unique(y_train)

plt.figure(figsize=(5,5))

for i, label in enumerate(unique_labels):

    image_index = np.where(y_train == label)[0][0]
    plt.subplot(5,5,i+1)
    plt.imshow(x_train[image_index].squeeze(), cmap='gray')
    plt.title(Uppercase[label])
    plt.axis('off')

plt.tight_layout()
plt.show()

# data -> 100 7:1:2


print("creating model")
#WHY?
model = models.Sequential([
    #find pattern amongst pixels
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),
    #make all into 1d array of inputs
    layers.Flatten(),
    layers.Dense(256, activation='relu'),
    #train 100 -> 70
    layers.Dropout(0.3),
    layers.Dense(24, activation='softmax')
])
model.summary()

"""Input: 28×28×1 grayscale image

1. Conv2D (32 filters, 3×3, ReLU)
   - Detects patterns like edges and shapes
   - Output: 26×26×32

2. MaxPooling2D (2×2)
   - Shrinks image, keeps strongest features
   - Output: 13×13×32

3. Flatten
   - Converts 3D feature maps into 1D vector
   - Output: 5408

4. Dense (256 neurons, ReLU)
   - Learns high-level features
   - Output: 256

5. Dropout (0.3)
   - Randomly disables 30% of neurons during training
   - Prevents overfitting
   - Output: 128

6. Dense (24 neurons, Softmax)
   - Outputs probabilities for 24 classes
   - Output: 24
"""

model.compile(
    optimizer='adam',
    loss= 'SparseCategoricalCrossentropy',
    metrics=['accuracy']
)

import numpy as np # Ensure numpy is imported

#training

# Define the unique labels from the training data
unique_labels_original = np.unique(y_train)

# Create a mapping from original labels to 0-indexed consecutive labels
label_map = {original_label: new_label for new_label, original_label in enumerate(unique_labels_original)}

# Apply the mapping to y_train and y_test
y_train_mapped = y_train.map(label_map)
y_test_mapped = y_test.map(label_map)

print("training model")
model.fit(
    x_train, y_train_mapped, # Use mapped labels here
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

print(label_map)



"""Using model"""

#using model
sample = x_train[1]
print(sample.shape)
pred = model.predict(np.expand_dims(sample, axis=0))
print(np.round(pred, decimals=2))

pred

print(y_train[0])

plt.plot(2,2)
plt.imshow(x_train[1].squeeze(), cmap='gray')
plt.title(Uppercase[y_train[1]])
plt.axis('off')

plt.tight_layout()
plt.show()

"""Plotting the loss graph and accuracy graph and confusion matrix of model

Confusion matrix: (where the model picked)
"""

from sklearn.metrics import confusion_matrix

y_prob = model.predict(x_test, verbose=0)
y_pred = np.argmax(y_prob, axis=1)
cm = confusion_matrix(y_test, y_pred)
print(cm)

np.round(y_prob, decimals=2)
#probability of what number per each time

y_pred
#what it chose (highest probability) or index of the highest number in probability in y_prob

print(np.bincount(y_test))
#how many times did 0,1,2,3... show up

print(np.bincount(y_pred))
#how many times did it predict 0,1,2...

print(np.unique(y_test))

confusion_matrix(np.array([1,3,3,1,2,2,1,1,3]), np.array([1,2,3,1,1,1,1,2,2]))
# confusion_matrix(lable,prediction) len(lable)=len(prediction)
# lable[1] and prediction[1] create a guess and lable pair
#  -  (each output nueron with what type of output and what the actual lable was)

model.save("sign_language_model.keras")

model_save = tf.keras.models.load_model("sign_language_model.keras")

